### ISSUE TITLE
View a Hunch Page

### ISSUE THREAD

**Issue by Bluestreak2k5** [global-pulse/HunchWorks#12]
The viewing of a Hunch page needs to be built, and their is no mockup for this.

For now we can store all the data from the Hunch in simple HTML tags.

**Comment by adgaudio** [comment]
From codejam:

Different viewpoints of hunches should include ordering by:
1. Most recent
2. Most active
3. User's hunches
4. User's interests (as related to hunch tags)
      a. Users need to have a list of interests

**Comment by Bluestreak2k5** [comment]
The view a hunch page now shows the hunch tags, the users working on the hunch with links to the user profiles, and the actual evidence attached to the hunch with its strength.

**Comment by Bluestreak2k5** [comment]
This issues is completed, but we will revisit this page in the next release. There are several issues still at hand that will need to be revisited. 
1. Need to display the type of evidence that it is right now. Current displays all evidence as tweets.
2. Need to display the strength of the evidence correctly. Currently it will always show up with a "+" before the number, even though strength is stored in the database. In the future strength will most likely not be in evidence.
3. Need to change the list of contributors to the creator and a link to all contributors, instead of the list it currently is. 
4. Need to programmitically determine the confidence level using equations that are yet to fully defined and developed. Currently they just show 40%.
