### ISSUE TITLE
Add Evidence to a Hunch

### ISSUE THREAD

**Issue by Bluestreak2k5** [global-pulse/HunchWorks#13]
Users need to be able to add evidence to new and existing hunches.

There is no mockup for this.

**Comment by adammck** [comment]
I'm implementing this in the `evidence_ui` branch in three steps:
1. Creating a custom `EvidenceField`, similar to the generic `TokenField`, which allows existing evidence objects to be searched (via ajax) and linked to the hunch.
2. Creating an `EvidenceForm` which allows evidence to be created. (This will eventually be used in a separate evidence-centric section, where evidence can be created without an associated hunch. For now, it's only useful in the context of hunches.)
3. Combine the two by allowing `EvidenceForm`s to be spawned and submitted on the client side. This will allow evidence to be created and linked to a hunch without leaving the hunch form.

**Comment by adammck** [comment]
Point three is not actually quite closed yet. Evidence can be added and removed from a hunch, but not created inline. This will come when evidence forms are created.
