### ISSUE TITLE
80% Test Coverage

### ISSUE THREAD

**Issue by adammck** [global-pulse/HunchWorks#41]
We're aiming to improve test coverage each cycle (i.e. keep up with the growth of the system). We're at 71% today (Oct 14th), so this isn't too ambitious.

**Comment by Bluestreak2k5** [comment]
Added tests for:
1. Hunches on groups page
2. Connections page
3. Open Hunches page
4. Finished Hunches page

**Comment by adammck** [comment]
Test coverage improved a lot during milestone two, but still isn't great. Bumping it to milestone three.

**Comment by Bluestreak2k5** [comment]
End of Wednesday coverage is 72%: Auth views now covered at 88%, everything except the invite people view, which doesn't send emails out anyway.

**Comment by Bluestreak2k5** [comment]
Removed unneeded Json views, added tests for Users and Albums views. Test Coverage at 79%

**Comment by Bluestreak2k5** [comment]
Need to rework helpers.**init**.py for testing votes, comments, and adding evidence

**Comment by adammck** [comment]
Test coverage is now 83%.
