### ISSUE TITLE
FactoryBoy to replace fixtures and test fixtures

### ISSUE THREAD

**Issue by adgaudio** [global-pulse/HunchWorks#50]
Rather than changing the fixtures every time we make a change, factoryboy dynamically generates model objects we need, factory style.   

See branch named 'factoryboy'

Currently working on UserProfile factory

**Comment by adgaudio** [comment]
Factoryboy sucks.  Implementing a better version.

**Comment by adgaudio** [comment]
Merged factoryboy branch to master.

fixturefactory.py replaces factoryboy.  

Todo:
    Support Many to Many
    Break up BaseFactory into 2 parts 
    Add more models from hunchworks.models

More soon

**Comment by adgaudio** [comment]
fixturefactory is done. 

 official repo here:  https://github.com/adgaudio/fixturefactory

just need to add some more models.  We currently have:

UserFactory
UserProfileFactory
ConnectionFaction

**Comment by adammck** [comment]
Great. Let's get this integrated on Monday, and get rid of our test fixtures.

**Comment by adammck** [comment]
I'm bumping this to the next milestone, since @adgaudio is dealing with it it isn't blocking anything.

**Comment by adgaudio** [comment]
Here is latest update:

fixturefactory 0.2 is available in cheeseshop (pypie)
Album test implements fixturefactory 0.2 for albums (but not evidence, etc)
Tests passed.

For all future tests, you can use fixturefactory.  See hunchworks/fixtures/factories.py and hunchworks/tests/albums.py for examples.

**Comment by Bluestreak2k5** [comment]
This now works and has been implemented into the tests.
