### ISSUE TITLE
Sample data should include Crisis Mappers examples

### ISSUE THREAD

**Issue by adammck** [global-pulse/HunchWorks#63]
Sara says that there are some good examples of the hunch/evidence/action workflow in the Dropbox and on the CM Google Group. Since those are real-world examples, we should use them as our sample data.

**Comment by Bluestreak2k5** [comment]
Found the data in Dropbox at
Global Pulse/Technology/HunchWorks Project/testing/hornofAfricadrought.doc

Not very useful for creating a real hunch, need to discuss with Sara.

**Comment by adammck** [comment]
This is clearly not happening, since the Crisis Mappers example isn't very useful. Closing without a resolution.
