### ISSUE TITLE
Dashboard is astoundingly ugly

### ISSUE THREAD

**Issue by adammck** [global-pulse/HunchWorks#68]

**Comment by adammck** [comment]
I'm doing a quick tidy-up of the dashboard. We need to actually design it, at some point.

**Comment by cvanderwalt** [comment]
Please use wireframes loaded today to github: https://github.com/global-pulse/HunchWorks/tree/master/Interface 
Let me know if you have any questions.

**Comment by adammck** [comment]
@cvanderwalt This is just a quick (mostly CSS) update to spare my eyes. We'll implement a proper dashboard when we have an actual spec. We spoke about (maybe) SVA focusing on that, but I'm not sure what became of that idea. Should we consider these wireframes a spec?

**Comment by cvanderwalt** [comment]
Use whatever is useful but ideally don't add anything.

On Tue, Oct 18, 2011 at 4:47 PM, Adam Mckaig <
reply@reply.github.com>wrote:

> @cvanderwalt This is just a quick (mostly CSS) update to spare my eyes.
> We'll implement a proper dashboard when we have an actual spec. We spoke
> about (maybe) SVA focusing on that, but I'm not sure what became of that
> idea. Should we consider these wireframes a spec?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/global-pulse/HunchWorks/issues/68#issuecomment-2447553

## 

Chris van der Walt
United Nations
mobile: +1 646 283 0177
email: vanderwalt@un.org http://www.unglobalpulse.org/

**Comment by cvanderwalt** [comment]
I think it is fairly similar to what you have been doing anyway.
