### ISSUE TITLE
Captions for Hunches and Groups

### ISSUE THREAD

**Issue by Bluestreak2k5** [global-pulse/HunchWorks#81]
Their needs to be a caption for hunches and groups pages on the create and edit forms. It currently doesn't make any sense to say "invite your conenctions" on the edit page.

**Comment by adammck** [comment]
Changing the captions is insufficient. I'm going to extract the permissions fields from the hunch edit form, and create new page to change them. They're already extracted in the hunch create page, so I might recycle that.

**Comment by adammck** [comment]
Closing this four year old bug.
